blog post: Using MicroProfile OpenAPI with RESTEasy
resteasy/resteasy.github.io pull request #114
Opened 2023-02-19 17:05 UTC by liweinan

2023-02-20 14:17 UTC, asoldano reviewed
@liweinan , how about a sentence at the beginning of the article to introduce the topic by saying what OpenAPI is and perhaps link to an Eclipse page about the specification?

2023-02-20 14:53 UTC, liweinan commented
> @liweinan , how about a sentence at the beginning of the article to introduce the topic by saying what OpenAPI is and perhaps link to an Eclipse page about the specification?

yes sir!

2023-02-20 17:10 UTC, jamezp requested changes
I'm not sure we should add all the information about the implementation details. Mentioning that WildFly uses smallrye-openapi is okay, but IMO we should focus more on the API and less on the implementation.

If we do feel the implementation details are okay, IMO they should be placed at the end of the blog post. As a user, you want to know how to use the MicroProfile OpenAPI with RESTEasy. Currently you'd have to read half the article before you can even run the example. I think users would feel overwhelmed with links to how Quarkus and WildFly implement the MicroProfile OpenAPI. It takes in depth knowledge of internals to understand the code. I don't think an average user really cares about that part of the story, but they want to have a nice working example of how to use the API's.

This is just my opinion so feel free to offer another opinion :)

2023-02-20 17:10 UTC, jamezp commented on _posts/2023-02-20-resteasy-microprofile-openapi.md
> +```
If we mention this, we should mention why. TBH the `management` layer is likely not required.

2023-02-20 17:10 UTC, jamezp commented on _posts/2023-02-20-resteasy-microprofile-openapi.md
> +```
Not critical at all, but you can simply run `mvn wildfly:run` and it will invoke the `package` phase.

2023-02-21 00:42 UTC, liweinan commented on _posts/2023-02-20-resteasy-microprofile-openapi.md
> +- [How to configure and run Maven WildFly plugin - Mastertheboss](http://www.mastertheboss.com/jboss-frameworks/jboss-maven/configuring-maven-wildfly-plugin/)
okay!

2023-02-21 00:42 UTC, liweinan commented on _posts/2023-02-20-resteasy-microprofile-openapi.md
> +In the underlying, Quarkus uses the `smallrye-open-api/extension-jaxrs`to generate the OpenAPI document. Here is the handler in Quarkus:
yes sir!

2023-02-21 00:44 UTC, liweinan commented on _posts/2023-02-20-resteasy-microprofile-openapi.md
> +- [Using OpenAPI and Swagger UI - Quarkus](https://quarkus.io/guides/openapi-swaggerui)
The rest APIs itself uses RESTEasy to provide the services, and on top of it, the Quarkus OpenAPI provides description to the services APIS. In addition the example in the articles relies on the dependency:

```txt
resteasy-reactive-jackson
```

Let me add a note on this.

2023-02-21 00:44 UTC, liweinan commented on _posts/2023-02-20-resteasy-microprofile-openapi.md
> +```
okay!

2023-02-21 00:45 UTC, liweinan commented on _posts/2023-02-20-resteasy-microprofile-openapi.md
> +```
yes sir!

2023-02-21 00:46 UTC, liweinan commented
> I'm not sure we should add all the information about the implementation details. Mentioning that WildFly uses smallrye-openapi is okay, but IMO we should focus more on the API and less on the implementation.
> 
> If we do feel the implementation details are okay, IMO they should be placed at the end of the blog post. As a user, you want to know how to use the MicroProfile OpenAPI with RESTEasy. Currently you'd have to read half the article before you can even run the example. I think users would feel overwhelmed with links to how Quarkus and WildFly implement the MicroProfile OpenAPI. It takes in depth knowledge of internals to understand the code. I don't think an average user really cares about that part of the story, but they want to have a nice working example of how to use the API's.

Yes sir! I'll adjust the content and put the implementation details as references into the bottom of the article :D

> 
> This is just my opinion so feel free to offer another opinion :)

2023-02-21 01:02 UTC, jamezp commented on _posts/2023-02-20-resteasy-microprofile-openapi.md
> +- [Using OpenAPI and Swagger UI - Quarkus](https://quarkus.io/guides/openapi-swaggerui)
It uses RESTEasy Reactive which is part of Quarkus. It doesn't use a version of RESTEasy we produce.

2023-02-21 01:15 UTC, liweinan commented on _posts/2023-02-20-resteasy-microprofile-openapi.md
> +- [Using OpenAPI and Swagger UI - Quarkus](https://quarkus.io/guides/openapi-swaggerui)
I'll adjust all these information into the last optional reading section of the article

2023-02-21 01:30 UTC, liweinan commented
@jamezp All the modifications are done! :D

2023-02-21 23:38 UTC, jamezp reviewed
Just a couple of minor comments.

2023-02-21 23:38 UTC, jamezp commented on _posts/2023-02-20-resteasy-microprofile-openapi.md
> +The above command will download the WildFly distribution, provision it and start the server, and then it will build and deploy the example as WAR, and then do the test.
We should probably state something more like:

The above command will build the example WAR. The integration tests will also be executed. Before the integration test, a server is provisioned and started.

Maybe not exactly that, but something similar. Really the part I find odd is the "download the WildFly distribution" because provisioning doesn't really download a distribution.

2023-02-21 23:38 UTC, jamezp commented on _posts/2023-02-20-resteasy-microprofile-openapi.md
> +To manually run the provisioned WildFly server, here is the command:
This command alone would provision a server and run it even if the server was already provisioned.

2023-02-21 23:38 UTC, jamezp commented on _posts/2023-02-20-resteasy-microprofile-openapi.md
> +And it uses `wildfly-galleon-pack` and `galleon-feature-pack` to provision the WildFly:
This should probably specify the groupId too only because one is from WildFly and one is from RESTEasy. Really the `org.jboss.resteasy:galleon-feature-pack` isn't even needed.

2023-02-22 09:34 UTC, liweinan commented
@jamezp all done!

2023-02-22 16:26 UTC, merged