RESTEASY-2740 - Write blog about WADL module deployment on Wildfly
resteasy/resteasy.github.io pull request #63
Opened 2021-01-18 07:46 UTC by liweinan

2021-01-18 08:30 UTC, asoldano requested changes
Thanks @liweinan ! I've added a few comments. In addition to them, please note you should be changing any `Wildfly` occurrence to `WildFly`;-)

2021-01-18 08:30 UTC, asoldano commented on _posts/2021-01-19-deploy-resteasy-wadl-to-wildfly.md
> +Please note the above solution maybe *unsafe*, because the resteasy-module version may not be integrated and tested by Wildfly team yet.
s/maybe/may be/

2021-01-18 08:30 UTC, asoldano commented on _posts/2021-01-19-deploy-resteasy-wadl-to-wildfly.md
> +From the above output, we can see the Wildfly on my machine is using RESTEasy `3.14.0.Final` by default. So the `resteasy-wadl` module you used better to keey sync with it, or there *may* have incomp
s/the Wildfly/WildFly/

2021-01-18 08:30 UTC, asoldano commented on _posts/2021-01-19-deploy-resteasy-wadl-to-wildfly.md
> +From the above output, we can see the Wildfly on my machine is using RESTEasy `3.14.0.Final` by default. So the `resteasy-wadl` module you used better to keey sync with it, or there *may* have incomp
I guess what you meant was something like: "... So `3.14.0.Final` is the version of the `resteasy-wadl` module I would want to use, or I might incur incompatibility issues."

2021-01-18 08:30 UTC, asoldano commented on _posts/2021-01-19-deploy-resteasy-wadl-to-wildfly.md
> +* [An example showing how to deploy resteasy-wadl based project to Wildfly](https://github.com/resteasy/resteasy-examples/blob/master/resteasy-wadl-wildfly/README.md)
It might be worth tagging the resteasy-examples project and change the URL here to refer to a tagged version. That way if we end up moving the example in a different directory, or renaming, etc. the link is not invalidated. Moreover, the assumption is that whatever is described here applies to the version that was available at the time of writing.

2021-01-19 01:10 UTC, ronsigal commented on _posts/2021-01-19-deploy-resteasy-wadl-to-wildfly.md
> +From the above output, we can see the Wildfly on my machine is using RESTEasy `3.14.0.Final` by default. So the `resteasy-wadl` module you used better to keey sync with it, or there *may* have incomp
s/keey sync/keep in sync/

2021-01-19 01:18 UTC, ronsigal commented on _posts/2021-01-19-deploy-resteasy-wadl-to-wildfly.md
> +Please note the above solution maybe *unsafe*, because the resteasy-module version may not be integrated and tested by Wildfly team yet.
When you say "resteasy-module version", you mean "RESTEasy version"?

2021-01-19 07:53 UTC, liweinan commented on _posts/2021-01-19-deploy-resteasy-wadl-to-wildfly.md
> +Please note the above solution maybe *unsafe*, because the resteasy-module version may not be integrated and tested by Wildfly team yet.
fixed

2021-01-19 07:53 UTC, liweinan commented on _posts/2021-01-19-deploy-resteasy-wadl-to-wildfly.md
> +From the above output, we can see the Wildfly on my machine is using RESTEasy `3.14.0.Final` by default. So the `resteasy-wadl` module you used better to keey sync with it, or there *may* have incomp
fixed

2021-01-19 07:53 UTC, liweinan commented on _posts/2021-01-19-deploy-resteasy-wadl-to-wildfly.md
> +From the above output, we can see the Wildfly on my machine is using RESTEasy `3.14.0.Final` by default. So the `resteasy-wadl` module you used better to keey sync with it, or there *may* have incomp
Much better!

2021-01-19 07:55 UTC, liweinan commented on _posts/2021-01-19-deploy-resteasy-wadl-to-wildfly.md
> +* [An example showing how to deploy resteasy-wadl based project to Wildfly](https://github.com/resteasy/resteasy-examples/blob/master/resteasy-wadl-wildfly/README.md)
okay!

2021-01-19 07:55 UTC, liweinan commented on _posts/2021-01-19-deploy-resteasy-wadl-to-wildfly.md
> +Please note the above solution maybe *unsafe*, because the resteasy-module version may not be integrated and tested by Wildfly team yet.
yes!

2021-01-19 07:55 UTC, liweinan commented on _posts/2021-01-19-deploy-resteasy-wadl-to-wildfly.md
> +From the above output, we can see the Wildfly on my machine is using RESTEasy `3.14.0.Final` by default. So the `resteasy-wadl` module you used better to keey sync with it, or there *may* have incomp
done

2021-01-19 07:57 UTC, liweinan commented
@asoldano @ronsigal Thanks for the help! I have fixed all the places you've suggested. Could you please help to review it? Thanks!

2021-01-19 18:01 UTC, ronsigal approved these changes
Well done!!

2021-01-20 01:19 UTC, merged